In [5]:
#trying out numpy 
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

arr =np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])

#slicing an array 
arr1= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1[5:])
print(arr1[:5])

#joing Two arrays using Pandas 



[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
2
3
[ 6  7  8  9 10 11 12]
[1 2 3 4 5]
