In [14]:
#trying out numpy 
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

arr =np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])

#slicing an array 
arr1= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1[5:])
print(arr1[:5])

#joing Two arrays using Pandas 
arr2 = np.array([12,13,14,15,16,17,18,19,20,21,22])
arr3 = np.array([22,23,24,25,26,27,28,29,30,31,32])
arrTotal =np.concatenate((arr2,arr3))
print(arrTotal)

#Converting data type with numpy
arrfloat = np.array([1.2,2.3,4.5])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)





[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
2
3
[ 6  7  8  9 10 11 12]
[1 2 3 4 5]
[12 13 14 15 16 17 18 19 20 21 22 22 23 24 25 26 27 28 29 30 31 32]
[1 2 3 4 5]
int32


In [20]:
#pandas is a python frame library used to create data frames 
#trying Out Pandas 
import pandas as pd
data ={
    "calories":[420,380,390,100,890,190], 
    "duration":[20,30,40,10,70,81] 
}

df = pd.DataFrame(data, index=["day1","day2","day3","day4","day5","day6"])

print(df)

      calories  duration
day1       420        20
day2       380        30
day3       390        40
day4       100        10
day5       890        70
day6       190        81
